server:
  port: 8086

spring:
  redis:
    port: 6379
    password: 8999958...***
    host: 123.207.64.43
    timeout: 100000
  thymeleaf:
    cache: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
